{
    "original_source": {
        "database(url)": "https://github.com/secureIT-project/CVEfixes",
        "software_system(CPE)": [
            "cpe:2.3:a:python:typed_ast:1.3.1:*:*:*:*:*:*:*",
            "cpe:2.3:a:python:typed_ast:1.3.0:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/python/typed_ast/commit/156afcb26c198e162504a57caddfe0acd9ed7dce",
        "version_end_excluding": {
            "python:typed_ast": "unknown"
        },
        "path": {
            "file_path": "typed_ast/__init__.py"
        }
    },
    "programming_language": "sql",
    "licences": {
        "database": "MIT",
        "affected_repository": "Other"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2019-19274"
        ],
        "CWE": [
            "CWE-125"
        ]
    }
}