{
    "original_source": {
        "database(url)": "https://github.com/secureIT-project/CVEfixes",
        "software_system(CPE)": [
            "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*",
            "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*",
            "cpe:2.3:a:google:tensorflow:2.7.0:rc1:*:*:*:*:*:*",
            "cpe:2.3:a:google:tensorflow:2.7.0:rc0:*:*:*:*:*:*",
            "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/tensorflow/tensorflow/commit/c79ba87153ee343401dbe9d1954d7f79e521eb14",
        "version_end_excluding": {
            "google:tensorflow": "2.4.4"
        },
        "path": {
            "file_path": "tensorflow/core/ops/array_ops.cc"
        }
    },
    "programming_language": "cpp",
    "licences": {
        "database": "MIT",
        "affected_repository": "Apache License 2.0"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2021-41216"
        ],
        "CWE": [
            "CWE-787"
        ]
    }
}