{
    "original_source": {
        "database(url)": "https://www.cve.org",
        "software_system(CPE)": [
            "cpe:2.3:a:lightningai:pytorch_lightning:*:*:*:*:*:python:*:*"
        ],
        "fix_commit": "https://github.com/pytorchlightning/pytorch-lightning/commit/62f1e82e032eb16565e676d39e0db0cac7e34ace",
        "version_end_excluding": {
            "lightningai:pytorch_lightning": "1.6.0"
        },
        "path": {
            "file_path": ""
        }
    },
    "programming_language": "PYTHON",
    "licences": {
        "database": "",
        "affected_repository": "Apache License 2.0"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2021-4118"
        ],
        "CWE": [
            "CWE-502"
        ]
    }
}