{
    "original_source": {
        "database(url)": "https://www.cve.org",
        "software_system(CPE)": [
            "cpe:2.3:a:setroubleshoot_project:setroubleshoot:*:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/fedora-selinux/setroubleshoot/commit/2d12677629ca319310f6263688bb1b7f676c01b7",
        "version_end_excluding": {
            "setroubleshoot_project:setroubleshoot": "unknown"
        },
        "path": {
            "file_path": ""
        }
    },
    "programming_language": "PYTHON",
    "licences": {
        "database": "",
        "affected_repository": "Unknown"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2016-4445"
        ],
        "CWE": []
    }
}