{
    "original_source": {
        "database(url)": "https://www.cve.org",
        "software_system(CPE)": [
            "cpe:2.3:a:jupyter:jupyter_core:*:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/jupyter/jupyter_core/commit/1118c8ce01800cb689d51f655f5ccef19516e283",
        "version_end_excluding": {
            "jupyter:jupyter_core": "4.11.2"
        },
        "path": {
            "file_path": ""
        }
    },
    "programming_language": "PYTHON",
    "licences": {
        "database": "",
        "affected_repository": "BSD 3-Clause \"New\" or \"Revised\" License"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2022-39286"
        ],
        "CWE": [
            "CWE-269",
            "CWE-250"
        ]
    }
}