{
    "original_source": {
        "database(url)": "https://www.cve.org",
        "software_system(CPE)": [
            "cpe:2.3:a:geosolutionsgroup:geonode:*:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/GeoNode/geonode/commit/79ac6e70419c2e0261548bed91c159b54ff35b8d",
        "version_end_excluding": {
            "geosolutionsgroup:geonode": "4.1.3"
        },
        "path": {
            "file_path": ""
        }
    },
    "programming_language": "PYTHON",
    "licences": {
        "database": "",
        "affected_repository": "Other"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2023-42439"
        ],
        "CWE": [
            "CWE-918"
        ]
    }
}