{
    "original_source": {
        "database(url)": "https://github.com/secureIT-project/CVEfixes",
        "software_system(CPE)": [
            "cpe:2.3:a:pyjwt_project:pyjwt:*:*:*:*:*:*:*:*",
            "cpe:2.3:o:fedoraproject:fedora:35:*:*:*:*:*:*:*",
            "cpe:2.3:o:fedoraproject:fedora:36:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/jpadilla/pyjwt/commit/9c528670c455b8d948aff95ed50e22940d1ad3fc",
        "version_end_excluding": {
            "pyjwt_project:pyjwt": "2.4.0",
            "fedoraproject:fedora": "unknown"
        },
        "path": {
            "file_path": "jwt/__init__.py"
        }
    },
    "programming_language": "python",
    "licences": {
        "database": "MIT",
        "affected_repository": "MIT License"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2022-29217"
        ],
        "CWE": [
            "CWE-327"
        ]
    }
}