{
    "original_source": {
        "database(url)": "https://github.com/secureIT-project/CVEfixes",
        "software_system(CPE)": [
            "cpe:2.3:a:yetiforce:yetiforce_customer_relationship_management:*:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/yetiforcecompany/yetiforcecrm/commit/8dccd93442725f245b4b71986bbe6f4f48639239",
        "version_end_excluding": {
            "yetiforce:yetiforce_customer_relationship_management": "unknown"
        },
        "path": {
            "file_path": "config/version.php"
        }
    },
    "programming_language": "php",
    "licences": {
        "database": "MIT",
        "affected_repository": "Other"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2021-4117"
        ],
        "CWE": [
            "CWE-20"
        ]
    }
}